#!/bin/bash
# Update & rebuild frontend only

source "$(dirname "$0")/envsetup.sh"

echo "Updating web-app..."
cd $FRONTEND_DIR || exit 1

# Pobierz najnowszy kod
git pull origin main

# Buduj i startuj kontener frontend
$DC build frontend
$DC up -d frontend
